spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gift_api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 500
        max-page-size: 1000
      page-serialization-mode: VIA_DTO
  liquibase:
    change-log: db/db.changelog-master.xml
    enabled: true
    drop-first: true
  servlet:
    multipart:
      max-file-size: 200MB

jdbc:
  batch-size: 10000

executor:
  core-pool-size: 1
  max-pool-size: 5
  queue-capacity: 20
  thread-name-prefix: "MyThread-"
  